# Generated by Django 5.2.1 on 2025-05-16 08:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0003_alter_client_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='CashBack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('client_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cashback', to='clients.client')),
            ],
            options={
                'verbose_name': 'CashBack',
                'verbose_name_plural': 'CashBacks',
            },
        ),
    ]
