# Generated by Django 5.2.1 on 2025-05-26 08:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashbacks', '0001_initial'),
        ('clients', '0005_rename_phone_number_whatsapp_client_phone_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='CashbackTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.PositiveBigIntegerField()),
                ('transaction_type', models.CharField(choices=[('EARNED', 'Earned'), ('USED', 'Used')], max_length=6)),
                ('cashback_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='сумма начислямого кэшбека')),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='сумма оплаты пользователя')),
                ('weight', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='вес')),
                ('balance_before', models.DecimalField(decimal_places=2, max_digits=10)),
                ('balance_after', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CashbackBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_earned', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='всего сколько начислено кешбэков')),
                ('total_used', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='всего сколько потрачено кешбэков')),
                ('current_balance', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='актуальный баланс кешбэка')),
                ('total_weight', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='всего сколько веса было')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cashback_balance', to='clients.client')),
            ],
        ),
        migrations.DeleteModel(
            name='CashBack',
        ),
    ]
