# Generated by Django 5.2.1 on 2025-05-26 08:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashbacks', '0002_cashbacktransaction_cashbackbalance_delete_cashback'),
        ('clients', '0005_rename_phone_number_whatsapp_client_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cashbacktransaction',
            name='client_id',
        ),
        migrations.AddField(
            model_name='cashbacktransaction',
            name='client',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='cashback_transactions', to='clients.client'),
            preserve_default=False,
        ),
    ]
