# Generated by Django 5.2.1 on 2025-05-16 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.CharField(max_length=8)),
                ('name', models.CharField(max_length=120)),
                ('surname', models.CharField(max_length=120)),
                ('phone_number', models.CharField(max_length=12)),
                ('phone_number_whatsapp', models.CharField(max_length=12)),
                ('city', models.CharField(max_length=120)),
                ('address', models.CharField(max_length=120)),
                ('ref_link', models.CharField(blank=True, max_length=120, null=True)),
                ('guanjou_address', models.CharField(max_length=1000)),
            ],
            options={
                'verbose_name': 'Client',
                'verbose_name_plural': 'Clients',
            },
        ),
    ]
