# Generated by Django 5.2.1 on 2025-05-16 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='client_id',
            new_name='client_code',
        ),
    ]
