# Generated by Django 5.2.1 on 2025-05-26 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_alter_client_address'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='guanjou_address',
            new_name='china_warehouse_address',
        ),
        migrations.RenameField(
            model_name='client',
            old_name='name',
            new_name='full_name',
        ),
        migrations.RenameField(
            model_name='client',
            old_name='phone_number',
            new_name='whatsapp_number',
        ),
        migrations.RemoveField(
            model_name='client',
            name='surname',
        ),
        migrations.AddField(
            model_name='client',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default="2025-01-01 00:00"),
            preserve_default=False,
        ),
    ]
