# Generated by Django 5.2.1 on 2025-05-26 03:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0004_rename_guanjou_address_client_china_warehouse_address_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='phone_number_whatsapp',
            new_name='phone_number',
        ),
    ]
