# Generated by Django 5.2.1 on 2025-05-26 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0005_rename_phone_number_whatsapp_client_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='full_name',
        ),
        migrations.AddField(
            model_name='client',
            name='first_name',
            field=models.CharField(default=1, max_length=60),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='client',
            name='last_name',
            field=models.CharField(default=1, max_length=60),
            preserve_default=False,
        ),
    ]
